-- Categories table (Optimized for filtering)
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  slug TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_categories_slug ON categories(slug);

-- Tutorials/Learning Path (Structured Content)
CREATE TABLE IF NOT EXISTS tutorials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  content TEXT NOT NULL, -- Markdown with code blocks
  difficulty TEXT CHECK (difficulty IN ('Beginner', 'Intermediate', 'Expert')) NOT NULL,
  section TEXT, -- e.g., "Network Defense", "Web Sploiting"
  commands JSONB DEFAULT '[]'::jsonb, -- Extracted commands for quick reference
  is_published BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_tutorials_slug ON tutorials(slug);
CREATE INDEX IF NOT EXISTS idx_tutorials_difficulty ON tutorials(difficulty);

-- Articles / Aggregated Content (High Volume)
CREATE TABLE IF NOT EXISTS articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  source_url TEXT NOT NULL UNIQUE,
  source_name TEXT NOT NULL,
  summary TEXT,
  content TEXT, -- Full content if scraping allowed
  extracted_commands JSONB DEFAULT '[]'::jsonb, -- Commands parsed from the text
  published_at TIMESTAMP WITH TIME ZONE,
  fetched_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  language TEXT DEFAULT 'fr', -- Target language
  categories JSONB DEFAULT '[]'::jsonb -- Tags/Categories
);

CREATE INDEX IF NOT EXISTS idx_articles_published_at ON articles(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_articles_source_name ON articles(source_name);

-- Standard Cheatsheets (Standalone)
CREATE TABLE IF NOT EXISTS cheatsheets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tool_name TEXT NOT NULL,
  category TEXT NOT NULL,
  command_data JSONB NOT NULL, -- Array of { description, command_line }
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS & Permissions
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE tutorials ENABLE ROW LEVEL SECURITY;
ALTER TABLE articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE cheatsheets ENABLE ROW LEVEL SECURITY;

-- Public Access Policies
CREATE POLICY "Public categories are viewable by everyone" ON categories FOR SELECT USING (true);
CREATE POLICY "Public tutorials are viewable by everyone" ON tutorials FOR SELECT USING (is_published = true);
CREATE POLICY "Public articles are viewable by everyone" ON articles FOR SELECT USING (true);
CREATE POLICY "Public cheatsheets are viewable by everyone" ON cheatsheets FOR SELECT USING (true);
